spring.application.name=demo-api-rest

# En src/main/resources/application.properties
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

#http://localhost:8080/actuator/metrics/jvm.memory.used
#http://localhost:8080/actuator/metrics/jvm.memory.max
#http://localhost:8080/actuator/metrics/jvm.gc.memory.promoted
#http://localhost:8080/actuator/metrics/jvm.memory.used{area=heap}
#http://localhost:8080/actuator/metrics/jvm.threads.live
management.endpoints.web.exposure.include=*
management.endpoint.metrics.enabled=true